"""Subclass of MainFrame, which is generated by wxFormBuilder."""

import wx
#from mainframe import MainFrame
from testframe import TestFrame
from MainFrame import MainFrame
from SettingsDialogImp import SettingsDialogImp
from fn_app import make_icon
from ObjectListView import ColumnDefn
import logging
import playground


# Implementing MainFrame
class MainFrameImp( MainFrame ):
#class MainFrameImp( TestFrame ):

	def __init__( self, parent ):
		MainFrame.__init__( self, parent )
		ico = wx.Icon('icons/disconnect2.ico', wx.BITMAP_TYPE_ICO)
		self.SetIcon(ico)
		#self.m_btnEditShelf.SetBitmap(wx.Bitmap('icons/Edit.png', wx.BITMAP_TYPE_PNG))
		self.m_btnEditShelf.SetBitmap(make_icon('Edit.png'))
		self.m_btnAddShelf.SetBitmap(make_icon('Add.png'))
		self.m_btnDeleteShelf.SetBitmap(make_icon('Cancel.png'))

		# testing objectlistview
		test_data = [{"name": "fred", "author": "mehungry"},
		 			 {"name": "vargos", "author": "renounced"}]
		self.shelf_list.SetColumns(
		 	[ColumnDefn("Name", "left", 220, "name"),
		 	 ColumnDefn("Author", "left", 200, "author")
		 	 ])
		self.shelf_list.SetObjects(test_data)
		self.shelf_list.Bind(wx.EVT_LIST_ITEM_SELECTED, self.select_item)

	def select_item(self, event):
		print("selected: ", self.shelf_list.GetSelectedObject()["name"])

	# Handlers for MainFrame events.
	def FileExportOnMenuSelection( self, event ):
		# TODO: Implement FileExportOnMenuSelection
		pass

	def menuFileQuitOnMenuSelection( self, event ):
		self.Close()

	def menuEditSettingsOnMenuSelection( self, event ):
		app = wx.App.Get()
		with SettingsDialogImp(self, app.data_directory) as dlg:
			if dlg.ShowModal() == wx.ID_OK:
				if dlg.dirty:
					# more than this needs to happen
					app.data_directory = dlg.data_directory

	def handle_menu_playground( self, event ):
		logging.warning("Playground")
		dlg = playground.PlaygroundForm(self)
		result = dlg.ShowModal()


	def OnNotebookPageChanged( self, event ):
		# TODO: Implement OnNotebookPageChanged
		pass

	def OnNotebookPageClose( self, event ):
		# TODO: Implement OnNotebookPageClose
		pass

	def AddShelfOnButtonClick( self, event ):
		# TODO: Implement AddShelfOnButtonClick
		pass

	def DeleteShelfOnButtonClick( self, event ):
		# TODO: Implement DeleteShelfOnButtonClick
		pass

	def EditShelfOnButtonClick( self, event ):
		# TODO: Implement EditShelfOnButtonClick
		pass

	def OnShelfColumnSort( self, event ):
		# TODO: Implement OnShelfColumnSort
		pass

	def OnShelfItemActivated( self, event ):
		# TODO: Implement OnShelfItemActivated
		pass

	def OnShelfSelectionChanged( self, event ):
		# TODO: Implement OnShelfSelectionChanged
		pass

	def AddSubjectOnButtonClick( self, event ):
		# TODO: Implement AddSubjectOnButtonClick
		pass

	def DeleteSubjectOnButtonClick( self, event ):
		# TODO: Implement DeleteSubjectOnButtonClick
		pass

	def EditSubjectOnButtonClick( self, event ):
		# TODO: Implement EditSubjectOnButtonClick
		pass

	def OnSubjectColumnSort( self, event ):
		# TODO: Implement OnSubjectColumnSort
		pass

	def OnSubjectItemActivated( self, event ):
		# TODO: Implement OnSubjectItemActivated
		pass

	def SubjectOnSelectionChanged( self, event ):
		# TODO: Implement SubjectOnSelectionChanged
		pass

	def AddPublicationOnButtonClick( self, event ):
		# TODO: Implement AddPublicationOnButtonClick
		pass

	def AddPublicationOnUpdateUI( self, event ):
		# TODO: Implement AddPublicationOnUpdateUI
		pass

	def DeletePublicationOnButtonClick( self, event ):
		# TODO: Implement DeletePublicationOnButtonClick
		pass

	def DeletePublicationOnUpdateUI( self, event ):
		# TODO: Implement DeletePublicationOnUpdateUI
		pass

	def EditPublicationOnButtonClick( self, event ):
		# TODO: Implement EditPublicationOnButtonClick
		pass

	def EditPublicationOnUpdateUI( self, event ):
		# TODO: Implement EditPublicationOnUpdateUI
		pass

	def OnPublicationColumnSort( self, event ):
		# TODO: Implement OnPublicationColumnSort
		pass

	def OnPublicationItemActivated( self, event ):
		# TODO: Implement OnPublicationItemActivated
		pass

	def PublicationSelectionChanged( self, event ):
		# TODO: Implement PublicationSelectionChanged
		pass




